Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2018-10, with the labels that each got.

#4 Parametrize ssh user
  pkg/e2e/framework/framework.go
  pkg/e2e/framework/machines.go
Labels: size/XS

#5 add tooling for CI
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/yaml-lint.sh
Labels: size/L

#7 Add OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#6 Make e2e framework reusable outside of e2e
  pkg/e2e/framework/clusterapi.go
  pkg/e2e/framework/clusters.go
  pkg/e2e/framework/framework.go
  pkg/e2e/framework/machines.go
  pkg/e2e/framework/ssh.go
  pkg/manifests/manifests.go
  pkg/manifests/userdata.go
Labels: approved, lgtm, size/L

#8 More owners
  OWNERS
Labels: approved, lgtm, size/XS

#9 Minor updates
  pkg/e2e/framework/clusterapi.go
  pkg/e2e/framework/framework.go
  pkg/e2e/framework/machines.go
Labels: approved, lgtm, size/M

#13 remove copyright notice
  Makefile
Labels: approved, lgtm, size/S

#12 Pass libvirt PK to the machine controller
  pkg/e2e/framework/clusterapi.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/S

#15 Fix fmt script invocation
  Makefile
  pkg/e2e/framework/machines.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#17 Logrus to glog
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XS

#18 Add missing subresource to CRDs
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XS

#16 Fix machine crd
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XS
