Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2019-08, with the labels that each got.

#102 e2e/infra: print time remaining in PollImmediate calls
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/M

#103 Use a cascading delete in drain test cleanup
  pkg/e2e/infra/infra.go
Labels: approved, lgtm, size/S

#105 Makefile: add -ginkgo.failFast to e2e invocations
  Makefile
Labels: approved, lgtm, size/S

#107 Makefile: ensure e2e/autoscaler tests run first in test-e2e target
  Makefile
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/S

#104 e2e/autoscaler: create all machinesets AOT
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/M

#106 e2e/framework: Bump WaitLong from 10m to 15m
  pkg/e2e/framework/common.go
Labels: approved, lgtm, size/XS

#108 e2e/infra: dump POD status in waitUntilAllRCPodsAreReady
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/S

#110 Use smaller names when creating transient MachineSets
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/infra/infra.go
Labels: approved, lgtm, size/XS

#112 Extend makefile with 'make goimports' target
  Makefile
  hack/goimports.sh
Labels: approved, lgtm, size/S

#113 e2e/autoscaler: add retry on conflict post scale down
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/XS

#111 bug 1713061: Pin dependencies to 4.1
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/cluster-autoscaler-operator/Gopkg.lock
  vendor/github.com/openshift/cluster-autoscaler-operator/Gopkg.toml
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/operator/status.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/operator/status_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
