Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2019-02, with the labels that each got.

#27 Add more RBAC rules to allow node draining
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#32 Rename labels from sigs.k8s.io to machine.openshift.io
  pkg/e2e/openshift/suites/smoke_suite.go
Labels: approved, lgtm, size/XS

#30 deps: switch cluster-api dependency to use master branch
  Gopkg.toml
Labels: approved, lgtm, size/XS

#33 update ownership
  OWNERS
Labels: approved, lgtm, size/XS

#35 Drop deprecated e2e and update Readme
  pkg/e2e/README.md
  pkg/e2e/openshift/main.go
  pkg/e2e/openshift/suites/e2e.go
  pkg/e2e/openshift/suites/smoke_suite.go
  pkg/e2e/openshift/suites/utils.go
Labels: approved, lgtm, size/XXL

#36 [autoscaling]: print which machines actually reference a node
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/XS
