Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2019-07, with the labels that each got.

#94 pkg/e2e/operators: Add tests for rejecting invalid CAO resources
  pkg/e2e/operators/cluster-autoscaler-operator.go
  pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/M

#95 README: Add instructions for running autoscaler tests under minikube
  README.md
Labels: approved, lgtm, size/L

#93 Increase workload and timeouts for Azure
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/S

#96 e2e: create required MachineSets as part of test setup
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/framework/common.go
  pkg/e2e/framework/framework.go
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/L

#101 Reduce timeouts back to their previous default pre-Azure
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/framework/common.go
Labels: approved, lgtm, size/XS

#100 e2e/autoscaler: dynamically compute workload size
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/S
