Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2019-03, with the labels that each got.

#34 MAO: add progressing/failing verification in available e2e check
  pkg/e2e/operators/cluster-autoscaler-operator.go
Labels: approved, lgtm, size/S

#41 Abstract function for 'have machines resources backing nodes' story
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
Labels: approved, do-not-merge/hold, lgtm, size/L

#43 Scaling stories
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/L

#45 Refactor deployments for operators
  pkg/e2e/operators/machine-api-operator.go
  pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/M

#44 Improve Taints validation
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/L

#46 e2e/autoscaler: remove ActiveDeadlineSeconds from job definition
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/XS

#48 e2e/autoscaler: Bump autoscaler workload timeout
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/XS

#49 Code improvements
  Makefile
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/framework/common.go
  pkg/e2e/framework/framework.go
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
  pkg/e2e/machinehealthcheck/machinehealthcheck.go
Labels: approved, lgtm, size/XL

#50 Move node draining under infra
  pkg/e2e/actuators/actuators.go
  pkg/e2e/e2e_test.go
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
Labels: approved, lgtm, size/XL

#52 Update cluster-api dep
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Makefile
  vendor/github.com/openshift/cluster-api/config/kustomization.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/consts.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/errors/machines.go
Labels: approved, lgtm, size/L

#53 Update readme implementation details
  pkg/e2e/README.md
Labels: approved, lgtm, size/S

#55 Bump k8s version and pin kubernetes-cni version
  pkg/manifests/userdata.go
Labels: approved, lgtm, size/XS
