Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2019-04, with the labels that each got.

#51 Refactor machine-health-check tests
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/framework/common.go
  pkg/e2e/framework/machinehealthcheck.go
  pkg/e2e/framework/machines.go
  pkg/e2e/framework/nodes.go
  pkg/e2e/infra/infra.go
  pkg/e2e/infra/utils.go
  pkg/e2e/machinehealthcheck/machinehealthcheck.go
Labels: approved, lgtm, ok-to-test, size/L

#57 Verify any invalid machineset is refused
  pkg/e2e/infra/infra.go
Labels: approved, lgtm, size/M

#58 Wait longer for clusterapi-manager-controllers deployment do re-appear
  pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/XS

#61 Increase wait time for nodes going ready
  pkg/e2e/framework/framework.go
  pkg/e2e/machinehealthcheck/machinehealthcheck.go
Labels: approved, lgtm, size/S

#59 e2e/operators/utils: Bump isDeploymentAvailable wait to long
  pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/XS

#63 Accommodate for new deployment name: machine-api-controllers
  pkg/e2e/operators/machine-api-operator.go
Labels: approved, lgtm, size/S

#71 Update vendor: cluster-api
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/cmd/manager/main.go
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/add_machinedeployment.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/M

#72 Rename sigs.k8s.io prefixed labels to machine.openshift.io prefixed labels
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/S

#69 Separate operators from functional test
  Makefile
  hack/ci-integration.sh
Labels: approved, lgtm, size/M

#65 Extend autoscaler test with multiple machineAutoscalerResource
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/L

#73 Revendor cluster api
  Gopkg.lock
  pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_cluster.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machinedeployment.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/machine_controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/openshift_controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/machinedeployment_controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/machineset_controller_test.go
Labels: approved, lgtm, size/XL

#75 Have ci-integration e2e workdir configurable
  hack/ci-integration.sh
Labels: approved, lgtm, size/XS

#74 Drop machine.io cluster
  Gopkg.lock
  pkg/e2e/framework/clusterapi.go
  pkg/e2e/framework/clusters.go
  pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/cluster_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/cluster_types_test.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/fake_cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/fake_machine_client.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/generic.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/expansion_generated.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/actuator.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/testactuator.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
  vendor/github.com/openshift/cluster-api/pkg/provider/example/actuators/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/provider/example/actuators/machine/machineactuator.go
Labels: approved, lgtm, size/XXL

#76 Remove status failing and update vendor
  Gopkg.lock
  Gopkg.toml
  pkg/e2e/operators/utils.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
Labels: approved, lgtm, size/L
