Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2019-06, with the labels that each got.

#84 Increase unneeded time to scale down a node
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/XS

#85 e2e/autoscaler: consume MaxNodesTotalReached event
  pkg/e2e/autoscaler/autoscaler.go
Labels: approved, lgtm, size/S

#86 Dump autoscaler logs before deleting the resource
  pkg/e2e/autoscaler/autoscaler.go
  pkg/e2e/framework/framework.go
Labels: approved, lgtm, size/M

#90 Switch to go 1.12
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  pkg/e2e/framework/framework.go
Labels: approved, lgtm, size/S

#87 Introduce a separate target to run tech preview e2e tests
  Makefile
  pkg/e2e/machinehealthcheck/machinehealthcheck.go
Labels: approved, lgtm, size/S
