Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2020-12, with the labels that each got.

#200 Bug 1880738: Add Dockerfile for CI step running mahcine-api e2e tests
  Dockerfile.ci
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#201 Improve resilience of autoscaler 12 nodes total test
  pkg/autoscaler/autoscaler.go
  pkg/framework/nodes.go
Labels: approved, lgtm

#192 Bug 1906732: Add E2E to ensure Cluster Wide Proxies are honoured in Machine API components
  docs/cluster-wide-proxy.md
  pkg/framework/daemonset.go
  pkg/framework/pods.go
  pkg/framework/proxies.go
  pkg/framework/services.go
  pkg/operators/machine-api-operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
