Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2020-01, with the labels that each got.

#130 [OCPCLOUD-765] Reduce test RC CPU to 40m
  pkg/e2e/infra/infra.go
Labels: approved, lgtm, size/XS

#129 [OCPCLOUD-763] Update instructions for running e2e tests
  README.md
Labels: approved, lgtm, size/L

#131 e2e: Prepend cluster name to machines in infra tests
  pkg/e2e/framework/common.go
  pkg/e2e/infra/infra.go
Labels: approved, lgtm, size/M

#132 OWNERS: remove frobware
  OWNERS
Labels: approved, lgtm, size/XS
