Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2023-08, with the labels that each got.

#289 testutils/vendoring: update openshift/api
  testutils/go.mod
  testutils/go.sum
  testutils/vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  testutils/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  testutils/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  testutils/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  testutils/vendor/github.com/openshift/api/config/v1/custom.infrastructure.testsuite.yaml
  testutils/vendor/github.com/openshift/api/config/v1/feature_gates.go
  testutils/vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  testutils/vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  testutils/vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  testutils/vendor/github.com/openshift/api/config/v1/types_feature.go
  testutils/vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  testutils/vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  testutils/vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  testutils/vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset.crd.yaml
  testutils/vendor/github.com/openshift/api/machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
  testutils/vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  testutils/vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  testutils/vendor/modules.txt
Labels: lgtm, approved

#292 OCPBUGS-17851: Update Azure zone to non-pointer
  go.mod
  go.sum
  testutils/go.mod
  testutils/go.sum
  testutils/resourcebuilder/machine/v1beta1/azure_provider_spec.go
  testutils/vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  testutils/vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  testutils/vendor/github.com/openshift/api/config/v1/types_feature.go
  testutils/vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  testutils/vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  testutils/vendor/modules.txt
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#291 Add assertion annotations to framework package
  pkg/framework/machines.go
  pkg/framework/machinesets.go
  pkg/framework/proxies.go
Labels: lgtm, approved

#293 OCPCLOUD-1717: Add annotations to error output
  pkg/providers/aws.go
Labels: lgtm, approved, jira/valid-reference

#295 Update README
  README.md
Labels: lgtm, approved

#297 OCPBUGS-18338: Fix CI by running tests natively by default
  Makefile
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#296 OCPCLOUD-1716: Add annotations to exceptions in operators pkg
  pkg/operators/cluster-autoscaler-operator.go
  pkg/operators/cluster-machine-approver.go
  pkg/operators/machine-api-operator.go
Labels: lgtm, approved, jira/valid-reference
