Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2024-12, with the labels that each got.

#344 OCPQE-26161,OCPBUGS-46552: Update labels to distinguish different tests
  Makefile
  pkg/autoscaler/autoscaler.go
  pkg/framework/ginkgo-labels.go
  pkg/infra/infra.go
  pkg/infra/lifecyclehooks.go
  pkg/infra/spot.go
  pkg/infra/webhooks.go
  pkg/machinehealthcheck/machinehealthcheck.go
  pkg/operators/cluster-autoscaler-operator.go
  pkg/operators/cluster-machine-approver.go
  pkg/operators/machine-api-operator.go
  pkg/providers/aws.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#342 Awscapi
  go.mod
  go.sum
  pkg/capi/aws.go
  pkg/e2e_test.go
  pkg/framework/aws_client.go
  pkg/framework/capi_machinesets.go
  pkg/framework/framework.go
  vendor/github.com/aws/aws-sdk-go/service/kms/api.go
  vendor/github.com/aws/aws-sdk-go/service/kms/doc.go
  vendor/github.com/aws/aws-sdk-go/service/kms/errors.go
  vendor/github.com/aws/aws-sdk-go/service/kms/service.go
  vendor/github.com/gregjones/httpcache/.travis.yml
  vendor/github.com/gregjones/httpcache/httpcache.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awscluster.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awscluster_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsclustercontrolleridentity_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsclusterroleidentity_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsclusterstaticidentity_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsclustertemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsclustertemplate_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsidentity_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachine_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachine_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachinetemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmachinetemplate_webhook.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/awsmanagedcluster_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/bastion.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/conditions_consts.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/defaults.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/network_types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/s3bucket.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/tags.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/types.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/webhooks.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2/zz_generated.defaults.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/feature/feature.go
  vendor/sigs.k8s.io/cluster-api-provider-aws/v2/feature/gates.go
Labels: lgtm, approved

#352 [release-4.17] OCPQE-26161,OCPBUGS-47522: update labels based on label proposal
  Makefile
  pkg/autoscaler/autoscaler.go
  pkg/framework/ginkgo-labels.go
  pkg/infra/infra.go
  pkg/infra/lifecyclehooks.go
  pkg/infra/spot.go
  pkg/infra/webhooks.go
  pkg/machinehealthcheck/machinehealthcheck.go
  pkg/operators/cluster-autoscaler-operator.go
  pkg/operators/cluster-machine-approver.go
  pkg/operators/machine-api-operator.go
  pkg/providers/aws.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#355 OCPQE-27801: enable capacityReservation case
  pkg/framework/aws_client.go
  pkg/providers/aws.go
Labels: lgtm, approved, jira/valid-reference

#364 OCPQE-27644: upd75396
  pkg/capi/aws.go
  pkg/framework/aws_client.go
Labels: lgtm, approved, jira/valid-reference

#365 [release-4.13] OCPQE-26161,OCPBUGS-47632: update labels based on label proposal
  Makefile
  pkg/autoscaler/autoscaler.go
  pkg/framework/ginkgo-labels.go
  pkg/infra/infra.go
  pkg/infra/lifecyclehooks.go
  pkg/infra/spot.go
  pkg/infra/webhooks.go
  pkg/machinehealthcheck/machinehealthcheck.go
  pkg/operators/cluster-autoscaler-operator.go
  pkg/operators/cluster-machine-approver.go
  pkg/operators/machine-api-operator.go
  pkg/providers/aws.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#368 [release-4.12] OCPBUGS-47544: add python script to handle test result so that can show in report portal
  .ci-operator.yaml
  pipeline/handleresult.py
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
