Repository openshift/cluster-api-actuator-pkg, pull requests merged in 2025-02, with the labels that each got.

#378 Adds ability to set disks to gcp provider builder
  testutils/resourcebuilder/machine/v1beta1/gcp_provider_spec.go
Labels: lgtm, approved

#379 Adds ability to set project to gcp provider builder
  testutils/resourcebuilder/machine/v1beta1/gcp_provider_spec.go
Labels: lgtm, approved

#374 OCPQE-27285: Fix the failures in qe ci jobs
  hack/ci-integration.sh
  pkg/framework/framework.go
  pkg/framework/machinesets.go
  pkg/infra/spot.go
  pkg/infra/webhooks.go
Labels: lgtm, approved, jira/valid-reference

#382 OCPQE-28631: update golang version
  Dockerfile.ci
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
